apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes: # Define volume
        - name: shared-log
          emptyDir: {}
      containers:
        - name: log-reader
          image: blackthest/log-reader:1.1
          volumeMounts: # Mount volume to container
            - name: shared-log
              mountPath: /shared
        - name: log-writer
          image: blackthest/log-writer:1.1
          volumeMounts: # Mount volume to container
            - name: shared-log
              mountPath: /shared